steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/physicianscopilot/pubmed-vectorizer:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/physicianscopilot/pubmed-vectorizer:latest']

images:
  - 'gcr.io/physicianscopilot/pubmed-vectorizer:latest'


options:
  logging: CLOUD_LOGGING_ONLY
